/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Auto-generated by OpenMechrevo protocol/codegen/codegen_kernel.py.
 * Architecture: Archetype Platform Base + Model Overrides.
 * Source files: docs/hw/registers.toml, docs/hw/archetypes, docs/hw/models
 *
 * Defines model-scoped register mappings and DMI matchers for Mechrevo laptops.
 */

#ifndef UNIWILL_MECHREVO_QUIRKS_H
#define UNIWILL_MECHREVO_QUIRKS_H

#include <linux/types.h>
#include <linux/dmi.h>
#include <linux/glob.h>

enum uniwill_cpu_vendor {
	UNIWILL_CPU_GENERIC = 0,
	UNIWILL_CPU_AMD = 1,
	UNIWILL_CPU_INTEL = 2,
};

enum uniwill_mux_scheme {
	UNIWILL_MUX_NONE = 0,
	UNIWILL_MUX_AMD = 1,   /* 0 = MSHybrid, 1 = dGPU, 2 = iGPU */
	UNIWILL_MUX_INTEL = 2, /* 4 = MSHybrid, 2 = dGPU, 1 = iGPU */
};

#define UNIWILL_MODE_OFFICE_BIT BIT(0)
#define UNIWILL_MODE_GAMING_BIT BIT(1)
#define UNIWILL_MODE_TURBO_BIT  BIT(2)
#define UNIWILL_MODE_CUSTOM_BIT BIT(3)

/*
 * Model-scoped register map and platform capability indirection table.
 * Generated by resolving archetype platform baselines with model overrides.
 */
struct uniwill_ec_regmap {
	const char *model_key;
	const char *model_name;
	u8 cpu_vendor;
	u8 supported_modes_mask;
	u8 has_dgpu;
	u8 has_mux;
	u8 mux_scheme;
	u8 has_dgpu_power_cut;
	u8 has_fan_table;
	u8 fan_channels;
	u8 fan_points;
	u8 fan_table_layout; /* 1 = FanTable1p5, 2 = FanTable2p0 */
	u16 reg_perf_mode;
	u16 reg_power_led;
	u16 reg_tdp_spl;
	u16 reg_tdp_sppt;
	u16 reg_tdp_fppt;
	u16 reg_tcc_offset;
	u16 reg_fan_curve_cpu;
	u16 reg_fan_curve_gpu;
	u16 reg_fan_curve_mid;
	u8 fan_down_temp_offset;
	u8 fan_duty_offset;
	u8 fan_duty_scale;
	u8 fan_gpu_up_temp_offset;
	u8 fan_gpu_down_temp_offset;
	u8 fan_boost_bit;
	u8 has_tdp_control;
	int tdp_spl_min;
	int tdp_spl_max;
	int tdp_sppt_min;
	int tdp_sppt_max;
	int tdp_fppt_min;
	int tdp_fppt_max;
	int tcc_offset_min;
	int tcc_offset_max;
};

/* Fallback register map ensuring zero regression on generic hardware */
static const struct uniwill_ec_regmap default_uniwill_regmap = {
	.model_key = "default",
	.model_name = "Generic Uniwill Device",
	.cpu_vendor = UNIWILL_CPU_GENERIC,
	.supported_modes_mask = UNIWILL_MODE_OFFICE_BIT | UNIWILL_MODE_GAMING_BIT,
	.has_dgpu = 0,
	.has_mux = 0,
	.mux_scheme = UNIWILL_MUX_NONE,
	.has_dgpu_power_cut = 0,
	.has_fan_table = 0,
	.fan_channels = 0,
	.fan_points = 0,
	.fan_table_layout = 0,
	.reg_perf_mode = 0x0751,
	.reg_power_led = 0x07A5,
	.reg_tdp_spl = 0x0783,
	.reg_tdp_sppt = 0x0784,
	.reg_tdp_fppt = 0x0785,
	.reg_tcc_offset = 0x0786,
	.reg_fan_curve_cpu = 0x0000,
	.reg_fan_curve_gpu = 0x0000,
	.reg_fan_curve_mid = 0x0000,
	.fan_down_temp_offset = 0,
	.fan_duty_offset = 0,
	.fan_duty_scale = 0,
	.fan_gpu_up_temp_offset = 0,
	.fan_gpu_down_temp_offset = 0,
	.fan_boost_bit = 6,
	.has_tdp_control = 0,
	.tdp_spl_min = 5,
	.tdp_spl_max = 45,
	.tdp_sppt_min = 5,
	.tdp_sppt_max = 45,
	.tdp_fppt_min = 5,
	.tdp_fppt_max = 54,
	.tcc_offset_min = 80,
	.tcc_offset_max = 100,
};

/* Model specific register mapping for Generic Uniwill / Tongfang Compatible */
static const struct uniwill_ec_regmap generic_uniwill_regmap = {
	.model_key = "GENERIC_UNIWILL",
	.model_name = "Generic Uniwill / Tongfang Compatible",
	.cpu_vendor = 0,
	.supported_modes_mask = 0x03,
	.has_dgpu = 0,
	.has_mux = 0,
	.mux_scheme = 0,
	.has_dgpu_power_cut = 0,
	.has_fan_table = 0,
	.fan_channels = 0,
	.fan_points = 0,
	.fan_table_layout = 0,
	.reg_perf_mode = 0x0751,
	.reg_power_led = 0x07A5,
	.reg_tdp_spl = 0x0783,
	.reg_tdp_sppt = 0x0784,
	.reg_tdp_fppt = 0x0785,
	.reg_tcc_offset = 0x0786,
	.reg_fan_curve_cpu = 0x0000,
	.reg_fan_curve_gpu = 0x0000,
	.reg_fan_curve_mid = 0x0000,
	.fan_down_temp_offset = 0x00,
	.fan_duty_offset = 0x00,
	.fan_duty_scale = 0,
	.fan_gpu_up_temp_offset = 0x00,
	.fan_gpu_down_temp_offset = 0x00,
	.fan_boost_bit = 6,
	.has_tdp_control = 0,
	.tdp_spl_min = 5,
	.tdp_spl_max = 45,
	.tdp_sppt_min = 5,
	.tdp_sppt_max = 45,
	.tdp_fppt_min = 5,
	.tdp_fppt_max = 54,
	.tcc_offset_min = 80,
	.tcc_offset_max = 100,
};

/* Model specific register mapping for Mechrevo 翼龙15 Pro (GM5HG0A) */
static const struct uniwill_ec_regmap gm5hg0a_regmap = {
	.model_key = "GM5HG0A",
	.model_name = "Mechrevo 翼龙15 Pro (GM5HG0A)",
	.cpu_vendor = 1,
	.supported_modes_mask = 0x0F,
	.has_dgpu = 1,
	.has_mux = 1,
	.mux_scheme = 1,
	.has_dgpu_power_cut = 1,
	.has_fan_table = 1,
	.fan_channels = 2,
	.fan_points = 16,
	.fan_table_layout = 1,
	.reg_perf_mode = 0x0751,
	.reg_power_led = 0x07A5,
	.reg_tdp_spl = 0x0783,
	.reg_tdp_sppt = 0x0784,
	.reg_tdp_fppt = 0x0785,
	.reg_tcc_offset = 0x0786,
	.reg_fan_curve_cpu = 0x0F00,
	.reg_fan_curve_gpu = 0x0F30,
	.reg_fan_curve_mid = 0x0000,
	.fan_down_temp_offset = 0x10,
	.fan_duty_offset = 0x20,
	.fan_duty_scale = 2,
	.fan_gpu_up_temp_offset = 0x00,
	.fan_gpu_down_temp_offset = 0x00,
	.fan_boost_bit = 6,
	.has_tdp_control = 1,
	.tdp_spl_min = 5,
	.tdp_spl_max = 90,
	.tdp_sppt_min = 5,
	.tdp_sppt_max = 90,
	.tdp_fppt_min = 5,
	.tdp_fppt_max = 100,
	.tcc_offset_min = 80,
	.tcc_offset_max = 100,
};

/* Model specific register mapping for Mechrevo 翼龙15 Intel (GM5IXxA) */
static const struct uniwill_ec_regmap gm5ixxa_regmap = {
	.model_key = "GM5IXxA",
	.model_name = "Mechrevo 翼龙15 Intel (GM5IXxA)",
	.cpu_vendor = 2,
	.supported_modes_mask = 0x0F,
	.has_dgpu = 1,
	.has_mux = 1,
	.mux_scheme = 2,
	.has_dgpu_power_cut = 1,
	.has_fan_table = 1,
	.fan_channels = 2,
	.fan_points = 16,
	.fan_table_layout = 1,
	.reg_perf_mode = 0x0751,
	.reg_power_led = 0x07A5,
	.reg_tdp_spl = 0x0783,
	.reg_tdp_sppt = 0x0784,
	.reg_tdp_fppt = 0x0785,
	.reg_tcc_offset = 0x0786,
	.reg_fan_curve_cpu = 0x0F00,
	.reg_fan_curve_gpu = 0x0F30,
	.reg_fan_curve_mid = 0x0000,
	.fan_down_temp_offset = 0x10,
	.fan_duty_offset = 0x20,
	.fan_duty_scale = 2,
	.fan_gpu_up_temp_offset = 0x00,
	.fan_gpu_down_temp_offset = 0x00,
	.fan_boost_bit = 6,
	.has_tdp_control = 1,
	.tdp_spl_min = 25,
	.tdp_spl_max = 140,
	.tdp_sppt_min = 25,
	.tdp_sppt_max = 160,
	.tdp_fppt_min = 25,
	.tdp_fppt_max = 175,
	.tcc_offset_min = 0,
	.tcc_offset_max = 20,
};

/* Model specific register mapping for Mechrevo 旷世16 Super (GM6IXxB) */
static const struct uniwill_ec_regmap gm6ixxb_regmap = {
	.model_key = "GM6IXxB",
	.model_name = "Mechrevo 旷世16 Super (GM6IXxB)",
	.cpu_vendor = 2,
	.supported_modes_mask = 0x0F,
	.has_dgpu = 1,
	.has_mux = 1,
	.mux_scheme = 2,
	.has_dgpu_power_cut = 1,
	.has_fan_table = 1,
	.fan_channels = 3,
	.fan_points = 16,
	.fan_table_layout = 2,
	.reg_perf_mode = 0x0751,
	.reg_power_led = 0x07A5,
	.reg_tdp_spl = 0x0783,
	.reg_tdp_sppt = 0x0784,
	.reg_tdp_fppt = 0x0785,
	.reg_tcc_offset = 0x0786,
	.reg_fan_curve_cpu = 0x0F00,
	.reg_fan_curve_gpu = 0x0F50,
	.reg_fan_curve_mid = 0x0FA0,
	.fan_down_temp_offset = 0x10,
	.fan_duty_offset = 0x20,
	.fan_duty_scale = 1,
	.fan_gpu_up_temp_offset = 0x30,
	.fan_gpu_down_temp_offset = 0x40,
	.fan_boost_bit = 6,
	.has_tdp_control = 1,
	.tdp_spl_min = 25,
	.tdp_spl_max = 140,
	.tdp_sppt_min = 25,
	.tdp_sppt_max = 160,
	.tdp_fppt_min = 25,
	.tdp_fppt_max = 175,
	.tcc_offset_min = 0,
	.tcc_offset_max = 20,
};

/* Model specific register mapping for Mechrevo 蛟龙16 (GMxRGxx) */
static const struct uniwill_ec_regmap gmxrgxx_regmap = {
	.model_key = "GMxRGxx",
	.model_name = "Mechrevo 蛟龙16 (GMxRGxx)",
	.cpu_vendor = 1,
	.supported_modes_mask = 0x0F,
	.has_dgpu = 1,
	.has_mux = 1,
	.mux_scheme = 1,
	.has_dgpu_power_cut = 1,
	.has_fan_table = 1,
	.fan_channels = 2,
	.fan_points = 16,
	.fan_table_layout = 1,
	.reg_perf_mode = 0x0751,
	.reg_power_led = 0x07A5,
	.reg_tdp_spl = 0x0783,
	.reg_tdp_sppt = 0x0784,
	.reg_tdp_fppt = 0x0785,
	.reg_tcc_offset = 0x0786,
	.reg_fan_curve_cpu = 0x0F00,
	.reg_fan_curve_gpu = 0x0F30,
	.reg_fan_curve_mid = 0x0000,
	.fan_down_temp_offset = 0x10,
	.fan_duty_offset = 0x20,
	.fan_duty_scale = 2,
	.fan_gpu_up_temp_offset = 0x00,
	.fan_gpu_down_temp_offset = 0x00,
	.fan_boost_bit = 6,
	.has_tdp_control = 1,
	.tdp_spl_min = 5,
	.tdp_spl_max = 90,
	.tdp_sppt_min = 5,
	.tdp_sppt_max = 90,
	.tdp_fppt_min = 5,
	.tdp_fppt_max = 100,
	.tcc_offset_min = 80,
	.tcc_offset_max = 100,
};

/* Model specific register mapping for Non-Tongfang Unsupported Machine */
static const struct uniwill_ec_regmap unsupported_non_tongfang_regmap = {
	.model_key = "UNSUPPORTED_NON_TONGFANG",
	.model_name = "Non-Tongfang Unsupported Machine",
	.cpu_vendor = 0,
	.supported_modes_mask = 0x00,
	.has_dgpu = 0,
	.has_mux = 0,
	.mux_scheme = 0,
	.has_dgpu_power_cut = 0,
	.has_fan_table = 0,
	.fan_channels = 0,
	.fan_points = 0,
	.fan_table_layout = 0,
	.reg_perf_mode = 0x0751,
	.reg_power_led = 0x07A5,
	.reg_tdp_spl = 0x0783,
	.reg_tdp_sppt = 0x0784,
	.reg_tdp_fppt = 0x0785,
	.reg_tcc_offset = 0x0786,
	.reg_fan_curve_cpu = 0x0000,
	.reg_fan_curve_gpu = 0x0000,
	.reg_fan_curve_mid = 0x0000,
	.fan_down_temp_offset = 0x00,
	.fan_duty_offset = 0x00,
	.fan_duty_scale = 0,
	.fan_gpu_up_temp_offset = 0x00,
	.fan_gpu_down_temp_offset = 0x00,
	.fan_boost_bit = 6,
	.has_tdp_control = 0,
	.tdp_spl_min = 0,
	.tdp_spl_max = 0,
	.tdp_sppt_min = 0,
	.tdp_sppt_max = 0,
	.tdp_fppt_min = 0,
	.tdp_fppt_max = 0,
	.tcc_offset_min = 80,
	.tcc_offset_max = 100,
};

/* Model specific register mapping for Mechrevo 无界14 Pro (WUJIE14P) */
static const struct uniwill_ec_regmap wujie14p_regmap = {
	.model_key = "WUJIE14P",
	.model_name = "Mechrevo 无界14 Pro (WUJIE14P)",
	.cpu_vendor = 1,
	.supported_modes_mask = 0x03,
	.has_dgpu = 0,
	.has_mux = 0,
	.mux_scheme = 0,
	.has_dgpu_power_cut = 0,
	.has_fan_table = 0,
	.fan_channels = 0,
	.fan_points = 0,
	.fan_table_layout = 0,
	.reg_perf_mode = 0x0751,
	.reg_power_led = 0x07A5,
	.reg_tdp_spl = 0x0783,
	.reg_tdp_sppt = 0x0784,
	.reg_tdp_fppt = 0x0785,
	.reg_tcc_offset = 0x0786,
	.reg_fan_curve_cpu = 0x0000,
	.reg_fan_curve_gpu = 0x0000,
	.reg_fan_curve_mid = 0x0000,
	.fan_down_temp_offset = 0x00,
	.fan_duty_offset = 0x00,
	.fan_duty_scale = 0,
	.fan_gpu_up_temp_offset = 0x00,
	.fan_gpu_down_temp_offset = 0x00,
	.fan_boost_bit = 6,
	.has_tdp_control = 1,
	.tdp_spl_min = 15,
	.tdp_spl_max = 54,
	.tdp_sppt_min = 15,
	.tdp_sppt_max = 65,
	.tdp_fppt_min = 15,
	.tdp_fppt_max = 75,
	.tcc_offset_min = 80,
	.tcc_offset_max = 100,
};

/*
 * DMI quirk match entry mapping system identifiers to model regmaps.
 * Note: Specific models must precede generic fallback rules.
 * Empty strings must never be used as match patterns in strstr().
 */
struct uniwill_dmi_regmap_entry {
	const char *vendor;
	const char *board_name;
	const char *product_name;
	const struct uniwill_ec_regmap *regmap;
};

static const struct uniwill_dmi_regmap_entry uniwill_dmi_regmap_table[] = {
	{ "MECHREVO", "GM5HG0A", NULL, &gm5hg0a_regmap },
	{ "MECHREVO", "GM5HG", NULL, &gm5hg0a_regmap },
	{ "MECHREVO", NULL, "yilong15", &gm5hg0a_regmap },
	{ "MECHREVO", NULL, "STELLSL15A06", &gm5hg0a_regmap },
	{ "MECHREVO", "*GM5IX?A*", NULL, &gm5ixxa_regmap },
	{ "MECHREVO", "GM5IX0A", NULL, &gm5ixxa_regmap },
	{ "MECHREVO", "GM5IX1A", NULL, &gm5ixxa_regmap },
	{ "MECHREVO", "GM5IX7A", NULL, &gm5ixxa_regmap },
	{ "MECHREVO", "GM5IX8A", NULL, &gm5ixxa_regmap },
	{ "MECHREVO", "GM5IX9A", NULL, &gm5ixxa_regmap },
	{ "MECHREVO", "GM5IX", NULL, &gm5ixxa_regmap },
	{ "MECHREVO", NULL, "STELLSL15I06", &gm5ixxa_regmap },
	{ "MECHREVO", NULL, "yilong15i", &gm5ixxa_regmap },
	{ "MECHREVO", "*GM6IX?B*", NULL, &gm6ixxb_regmap },
	{ "MECHREVO", "GM6IX0B", NULL, &gm6ixxb_regmap },
	{ "MECHREVO", "GM6IX1B", NULL, &gm6ixxb_regmap },
	{ "MECHREVO", "GM6IX7B", NULL, &gm6ixxb_regmap },
	{ "MECHREVO", "GM6IX8B", NULL, &gm6ixxb_regmap },
	{ "MECHREVO", "GM6IX9B", NULL, &gm6ixxb_regmap },
	{ "MECHREVO", NULL, "kuangshi16", &gm6ixxb_regmap },
	{ "MECHREVO", NULL, "STELLARIS16I06", &gm6ixxb_regmap },
	{ "MECHREVO", "GM5RG", NULL, &gmxrgxx_regmap },
	{ "MECHREVO", "GM6RG", NULL, &gmxrgxx_regmap },
	{ "MECHREVO", "*GM?RG*", NULL, &gmxrgxx_regmap },
	{ "MECHREVO", "*GM*RG*", NULL, &gmxrgxx_regmap },
	{ "MECHREVO", NULL, "jiaolong", &gmxrgxx_regmap },
	{ "MECHREVO", NULL, "STEPOL1XA04", &gmxrgxx_regmap },
	{ "MECHREVO", NULL, "POLARIS1XA05", &gmxrgxx_regmap },
	{ "MECHREVO", "PF4MU", NULL, &wujie14p_regmap },
	{ "MECHREVO", "PF5MU", NULL, &wujie14p_regmap },
	{ "MECHREVO", "WUJIE14P", NULL, &wujie14p_regmap },
	{ "MECHREVO", NULL, "wujie14", &wujie14p_regmap },
	{ "MECHREVO", NULL, "code01", &wujie14p_regmap },
	{ NULL, NULL, NULL, NULL }
};

/*
 * Matches string with either shell glob pattern or substring search.
 * Zero heap allocation, safe for early boot and kernel DMI matching.
 */
static inline bool uniwill_dmi_match_string(const char *pattern, const char *str)
{
	if (!pattern || !str)
		return false;
	if (strchr(pattern, '*') || strchr(pattern, '?') || strchr(pattern, '['))
		return glob_match(pattern, str);
	return strstr(str, pattern) != NULL;
}

/* Lookup model regmap from system DMI table */
static inline const struct uniwill_ec_regmap *uniwill_match_ec_regmap(void)
{
	const struct uniwill_dmi_regmap_entry *entry;
	const char *sys_vendor = dmi_get_system_info(DMI_SYS_VENDOR);
	const char *board_vendor = dmi_get_system_info(DMI_BOARD_VENDOR);
	const char *board_name = dmi_get_system_info(DMI_BOARD_NAME);
	const char *product_name = dmi_get_system_info(DMI_PRODUCT_NAME);
	bool is_mechrevo = false;

	if ((sys_vendor && strstr(sys_vendor, "MECHREVO")) ||
	    (board_vendor && strstr(board_vendor, "MECHREVO")))
		is_mechrevo = true;

	/* Pass 1: Strict board_name match (highest priority) */
	for (entry = uniwill_dmi_regmap_table; entry->regmap != NULL; entry++) {
		if (!entry->board_name)
			continue;
		if (entry->vendor) {
			bool vendor_match = false;
			if (sys_vendor && strstr(sys_vendor, entry->vendor))
				vendor_match = true;
			if (board_vendor && strstr(board_vendor, entry->vendor))
				vendor_match = true;
			if (!vendor_match)
				continue;
		}
		if (board_name && uniwill_dmi_match_string(entry->board_name, board_name))
			return entry->regmap;
	}

	/* Pass 2: Secondary product_name match */
	for (entry = uniwill_dmi_regmap_table; entry->regmap != NULL; entry++) {
		if (!entry->product_name)
			continue;
		if (entry->vendor) {
			bool vendor_match = false;
			if (sys_vendor && strstr(sys_vendor, entry->vendor))
				vendor_match = true;
			if (board_vendor && strstr(board_vendor, entry->vendor))
				vendor_match = true;
			if (!vendor_match)
				continue;
		}
		if (product_name && uniwill_dmi_match_string(entry->product_name, product_name))
			return entry->regmap;
	}

	/* If MECHREVO vendor detected but specific model not matched, fall back to generic */
	if (is_mechrevo)
		return &generic_uniwill_regmap;

	return &default_uniwill_regmap;
}

#endif /* UNIWILL_MECHREVO_QUIRKS_H */
